name: Go

on:
  push:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'  # Добавляем конкретную версию Go

      - name: Build
        run: go build -v ./...

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Test
        run: |
          go test -v ./...
          go clean -testcache  # Очистка временных файлов после тестов

  tests-race:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Test with race detector
        run: |
          go test -race -v ./...
          go clean -testcache  # Очистка временных файлов после тестов
  
  lint:
    needs: [tests, tests-race]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - uses: golangci/golangci-lint-action@v3
        with:
          skip-files: # Добавьте конкретные настройки для golangci-lint, если нужно
            - "**/testdata/**"